### ISSUE TITLE
Contour corrections

### ISSUE THREAD

**Issue by StefanPeev** [feerus23/Makisans#4]
Have you an idea to develop this project? All the contours need corrections - as a first step through adding extremas. In the image below all the circles with cross inside them mark the places where are extremas. Do you need some help?

![Screenshot 2023-08-19 211641](https://github.com/feerus23/MakiSans/assets/12949369/44bef1bd-45fa-4d25-b4bd-01f3f3fbd39b)

**Comment by svrfee** [comment]
Hello, I did not delve into the topic of font development and created this one rather for myself and practice, but posted it online, because why not? All glyphs were created by tracing images, characters drawn with a brush in Photoshop. I am not sure that I will return to finalizing the font in the near future, but sooner or later I will finish it. I would be grateful if you could help provide good font development materials in this style. Sorry for my MTL english.

**Comment by svrfee** [comment]
I decided to redraw again. In the past times, I just drew on the gp, made a stroke outline in the illustrator and exported it to FontForge. Now I decided to try to do it wisely.
